FROM python:3.7-buster
WORKDIR /server
RUN wget -O /usr/local/bin/bazel "https://github.com/bazelbuild/bazel/releases/download/3.2.0/bazel-3.2.0-linux-x86_64"\
&& chmod +x /usr/local/bin/bazel
COPY BUILD /server
COPY WORKSPACE /server
COPY requirements.txt /server
COPY proto/ /server/proto
RUN bazel build //proto:all
COPY server/ /server/server
RUN bazel build //server:blackbox_server
RUN mkdir /server/data_folder
CMD ["bazel", "run", "//server:blackbox_server"]