version: '3.8'
services:
  blackbox-worker:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: solonkovda/blackbox_optimization_worker:master
    environment:
      DATA_FOLDER: /worker/data_folder
      SERVER_ADDRESS: ${SERVER_ADDRESS:?no server address specified}
      PYTHONUNBUFFERED: 1
      HEARTBEAT_TIME:
      RESPONSE_DELAY:
      MAX_WORKERS:
      MAX_JOBS_PER_ACTIVE_WORKER:
